module.exports = [
  ["infed.org: – education, community-building and change", "https://infed.org/mobi/"],
  ["Modern Different", "https://moderndifferent.com"],
  ["A Sustainable Internet for All - Branch", "https://branch.climateaction.tech"],
  ["WikiArt.org - Visual Art Encyclopedia", "https://www.wikiart.org/"],
  ["SFPC | School for Poetic Computation", "https://sfpc.io/"],
  ["Zero Data App", "https://0data.app/"],
  ["The Kool Aid Factory :: All Zines", "https://koolaidfactory.com"],
  ["Critical Atlas of Internet", "https://louisedrulhe.fr/internet-atlas/"],
  ["For New Readers - RibbonFarm", "https://www.ribbonfarm.com/for-new-readers/"],
  ["Wealth, shown to scale", "https://mkorostoff.github.io/1-pixel-wealth/"],
  ["Global Grey ebooks: download free ebooks for your library", "https://www.globalgreyebooks.com/index.html"],
  ["The Public Domain Review – Online journal dedicated to showcasing", "https://publicdomainreview.org"],
  ["The Manual", "https://manual.withcompound.com"],
  ["Museum of Endangered Sounds", "http://savethesounds.info"],
  ["Better Computer Grants", "https://makeabetter.computer/"],
  ["PATRICK TRESSET | Patrick Tresset is a Brussels based artist", "https://patricktresset.com/new/"],
  ["Virtual Lab by Quantum Flytrap", "https://lab.quantumflytrap.com/lab?mode=waves"],
  ["https://how-i-experience-web-today.com/detail.html#", "https://how-i-experience-web-today.com/detail.html#"],
  ["Fold ’N Fly » Paper Airplane Folding Instructions", "https://www.foldnfly.com/#/1-1-1-1-1-1-1-1-2"],
  ["Weird Old Book Finder", "https://weird-old-book-finder.glitch.me/"],
  ["https://standardebooks.org/", "https://standardebooks.org/"],
  ["Recommend Me a Book", "https://recommendmeabook.com/"],
  ["The New Cavalier Reading Society | ·only·the·wise·are·free·", "https://newcavalierreadingsociety.com/"],
  ["Notable people", "https://tjukanovt.github.io/notable-people"],
  ["Omniglot - the encyclopedia of writing systems and languages", "https://omniglot.com/index.htm"],
  ["GRASS ROOTS HOUSING PROCESS", "https://www.livingneighborhoods.org/library/grassroots.htm"],
  ["Essays · Gwern.net", "https://www.gwern.net/"],
  ["MAKE MY DRIVE FUN", "https://makemydrivefun.com/"],
  ["Cards of Logic", "https://www.cardsoflogic.com/"],
  ["The Cursed Computer Iceberg Meme", "https://suricrasia.online/iceberg/"],
  ["50,000+ Free eBooks in the Genres you Love | Manybooks", "https://manybooks.net/"],
  ["Bird Migration Explorer", "https://explorer.audubon.org/home?threatOverlay=expand&zoom=3&x=1306099.1620122588&y=281"]
]
